import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import testEmailRouter from "./test-email";
import usersRouter from "./users";
import membershipRouter from "./membership";
import paymentsRouter from "./payments";
import contentRouter from "./content";
import dashboardRouter from "./dashboard";
import adminRouter from "./admin";
import documentsRouter from "./documents";
import storageRouter from "./storage";
import reviewsRouter from "./reviews";
import profileRouter from "./profile";
import creditsRouter from "./credits";
import supportRouter from "./support";
import visionRouter from "./vision";
import geminiOcrRouter from "./gemini-ocr";
import unsplashRouter from "./unsplash";
import pixabayRouter from "./pixabay";
import walletRouter from "./wallet";
import rechargeRouter from "./recharge";
import kycRouter from "./kyc";
import tpinRouter from "./tpin";
import adminRechargeRouter from "./admin-recharge";
import adminReportsRouter from "./admin-reports";
import operatorMembershipRouter from "./operator-membership";
import serviceRequestRouter from "./service-request";
import moneyRouter from "./money";
import couponsRouter from "./coupons";
import liveDataRouter from "./live-data";
import newsRouter from "./news";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(testEmailRouter);
router.use(usersRouter);
router.use(membershipRouter);
router.use(paymentsRouter);
router.use(contentRouter);
router.use(dashboardRouter);
router.use(adminRouter);
router.use(documentsRouter);
router.use(storageRouter);
router.use(reviewsRouter);
router.use(profileRouter);
router.use(creditsRouter);
router.use(supportRouter);
router.use(visionRouter);
router.use(geminiOcrRouter);
router.use(unsplashRouter);
router.use(pixabayRouter);
router.use(walletRouter);
router.use(rechargeRouter);
router.use(kycRouter);
router.use(tpinRouter);
router.use(adminRechargeRouter);
router.use(adminReportsRouter);
router.use(operatorMembershipRouter);
router.use(serviceRequestRouter);
router.use(moneyRouter);
router.use(couponsRouter);
router.use(liveDataRouter);
router.use(newsRouter);

export default router;
