/**
 * Cascading geo data for the Weather panel: state → district → towns.
 *
 * - Gujarat is comprehensively covered (all 33 districts, with major
 *   talukas / towns under each) since the platform's primary audience
 *   is Gujarati CSC operators.
 * - Other states list their well-known districts; the "towns" array
 *   defaults to the district HQ when sub-town granularity is not
 *   curated. Users in those states can still pick a district + town
 *   and OpenWeatherMap geocoding will resolve to the nearest match.
 *
 * This is intentionally a static curated list rather than a dynamic
 * upstream call: there is no free, reliable, India-wide
 * district→block dataset, and this list provides a fast, predictable
 * cascade experience without an API hit per dropdown.
 */

export type DistrictMap = Record<string, string[]>;
export type StateDistrictMap = Record<string, DistrictMap>;

export const IN_DISTRICTS: StateDistrictMap = {
  Gujarat: {
    Ahmedabad: ["Ahmedabad", "Sanand", "Dholka", "Bavla", "Viramgam", "Dhandhuka"],
    Amreli: ["Amreli", "Savarkundla", "Rajula", "Babra", "Lathi", "Lilia"],
    Anand: ["Anand", "Petlad", "Borsad", "Khambhat", "Umreth", "Anklav"],
    Aravalli: ["Modasa", "Bayad", "Dhansura", "Malpur", "Meghraj"],
    Banaskantha: ["Palanpur", "Deesa", "Tharad", "Vadgam", "Dhanera", "Amirgadh"],
    Bharuch: ["Bharuch", "Ankleshwar", "Jambusar", "Vagra", "Hansot", "Amod"],
    Bhavnagar: ["Bhavnagar", "Sihor", "Palitana", "Mahuva", "Talaja", "Gariadhar"],
    Botad: ["Botad", "Barwala", "Gadhada", "Ranpur"],
    "Chhota Udaipur": ["Chhota Udaipur", "Bodeli", "Sankheda", "Pavi Jetpur", "Kawant"],
    Dahod: ["Dahod", "Devgadh Baria", "Limkheda", "Jhalod", "Garbada", "Sanjeli"],
    Dang: ["Ahwa", "Waghai", "Subir"],
    "Devbhoomi Dwarka": ["Khambhalia", "Dwarka", "Bhanvad", "Kalyanpur"],
    Gandhinagar: ["Gandhinagar", "Kalol", "Mansa", "Dehgam"],
    "Gir Somnath": ["Veraval", "Una", "Kodinar", "Sutrapada", "Talala"],
    Jamnagar: ["Jamnagar", "Dhrol", "Jodiya", "Kalavad", "Lalpur", "Jamjodhpur"],
    Junagadh: [
      "Junagadh",
      "Manavadar",
      "Vanthali",
      "Visavadar",
      "Bhesan",
      "Mendarda",
      "Keshod",
      "Mangrol",
      "Malia Hatina",
    ],
    Kheda: ["Nadiad", "Kheda", "Kapadvanj", "Mahudha", "Mehmedabad", "Thasra", "Matar"],
    Kutch: [
      "Bhuj",
      "Gandhidham",
      "Anjar",
      "Mandvi",
      "Mundra",
      "Nakhatrana",
      "Bhachau",
      "Rapar",
      "Lakhpat",
      "Abdasa",
    ],
    Mahisagar: ["Lunawada", "Santrampur", "Balasinor", "Khanpur", "Kadana", "Virpur"],
    Mehsana: ["Mehsana", "Visnagar", "Vijapur", "Unjha", "Kheralu", "Becharaji", "Vadnagar"],
    Morbi: ["Morbi", "Wankaner", "Tankara", "Maliya"],
    Narmada: ["Rajpipla", "Dediapada", "Sagbara", "Tilakwada", "Garudeshwar"],
    Navsari: ["Navsari", "Bilimora", "Jalalpore", "Gandevi", "Vansda", "Chikhli"],
    Panchmahal: ["Godhra", "Halol", "Kalol", "Shehera", "Morwa Hadaf", "Jambughoda", "Ghoghamba"],
    Patan: ["Patan", "Sidhpur", "Chanasma", "Radhanpur", "Harij", "Sami", "Santalpur"],
    Porbandar: ["Porbandar", "Ranavav", "Kutiyana"],
    Rajkot: ["Rajkot", "Gondal", "Jetpur", "Dhoraji", "Upleta", "Jasdan", "Lodhika"],
    Sabarkantha: ["Himmatnagar", "Idar", "Khedbrahma", "Vadali", "Talod", "Prantij"],
    Surat: ["Surat", "Bardoli", "Mandvi", "Vyara", "Olpad", "Kamrej", "Mahuva", "Songadh"],
    Surendranagar: ["Surendranagar", "Wadhwan", "Limbdi", "Dhrangadhra", "Chotila", "Sayla"],
    Tapi: ["Vyara", "Songadh", "Uchchhal", "Nizar", "Valod", "Dolvan"],
    Vadodara: ["Vadodara", "Padra", "Karjan", "Savli", "Dabhoi", "Sinor", "Waghodia"],
    Valsad: ["Valsad", "Vapi", "Pardi", "Umbergaon", "Dharampur", "Kaprada"],
  },

  // For non-Gujarat states we curate well-known districts only; the
  // town dropdown defaults to the district HQ name. OWM geocoding
  // resolves these reliably with `,<state>,IN` suffix.
  "Andhra Pradesh": singleTownDistricts([
    "Anantapur",
    "Chittoor",
    "East Godavari",
    "Guntur",
    "Krishna",
    "Kurnool",
    "Nellore",
    "Prakasam",
    "Srikakulam",
    "Visakhapatnam",
    "Vizianagaram",
    "West Godavari",
    "YSR Kadapa",
    "Tirupati",
  ]),
  "Arunachal Pradesh": singleTownDistricts([
    "Itanagar",
    "Tawang",
    "West Kameng",
    "East Kameng",
    "Papum Pare",
    "Lower Subansiri",
    "Upper Subansiri",
    "West Siang",
    "East Siang",
    "Changlang",
  ]),
  Assam: singleTownDistricts([
    "Guwahati",
    "Dibrugarh",
    "Silchar",
    "Jorhat",
    "Tezpur",
    "Nagaon",
    "Tinsukia",
    "Bongaigaon",
    "Barpeta",
    "Dhubri",
    "Karimganj",
    "Sivasagar",
  ]),
  Bihar: singleTownDistricts([
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Purnia",
    "Begusarai",
    "Katihar",
    "Munger",
    "Chapra",
    "Hajipur",
    "Ara",
    "Nalanda",
    "Sasaram",
    "Motihari",
  ]),
  Chandigarh: { Chandigarh: ["Chandigarh"] },
  Chhattisgarh: singleTownDistricts([
    "Raipur",
    "Bilaspur",
    "Bhilai",
    "Durg",
    "Korba",
    "Raigarh",
    "Jagdalpur",
    "Ambikapur",
    "Rajnandgaon",
    "Dhamtari",
  ]),
  "Dadra and Nagar Haveli": { Silvassa: ["Silvassa"] },
  "Daman and Diu": { Daman: ["Daman"], Diu: ["Diu"] },
  Delhi: singleTownDistricts([
    "New Delhi",
    "North Delhi",
    "South Delhi",
    "East Delhi",
    "West Delhi",
    "Central Delhi",
    "North East Delhi",
    "North West Delhi",
    "South East Delhi",
    "South West Delhi",
    "Shahdara",
  ]),
  Goa: { "North Goa": ["Panaji", "Mapusa", "Bicholim"], "South Goa": ["Margao", "Vasco", "Ponda"] },
  Haryana: singleTownDistricts([
    "Gurugram",
    "Faridabad",
    "Panipat",
    "Karnal",
    "Hisar",
    "Rohtak",
    "Sonipat",
    "Ambala",
    "Yamunanagar",
    "Bhiwani",
    "Sirsa",
    "Kurukshetra",
    "Panchkula",
    "Rewari",
    "Jhajjar",
  ]),
  "Himachal Pradesh": singleTownDistricts([
    "Shimla",
    "Kangra",
    "Mandi",
    "Solan",
    "Hamirpur",
    "Una",
    "Bilaspur",
    "Chamba",
    "Kullu",
    "Kinnaur",
    "Lahaul and Spiti",
    "Sirmaur",
  ]),
  "Jammu and Kashmir": singleTownDistricts([
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Udhampur",
    "Kathua",
    "Kupwara",
    "Pulwama",
    "Doda",
    "Rajouri",
    "Poonch",
  ]),
  Jharkhand: singleTownDistricts([
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Hazaribagh",
    "Deoghar",
    "Giridih",
    "Ramgarh",
    "Palamu",
    "Chaibasa",
  ]),
  Karnataka: singleTownDistricts([
    "Bengaluru",
    "Mysuru",
    "Hubli",
    "Mangalore",
    "Belagavi",
    "Kalaburagi",
    "Davangere",
    "Ballari",
    "Tumkur",
    "Shimoga",
    "Vijayapura",
    "Raichur",
    "Hassan",
    "Udupi",
    "Chitradurga",
  ]),
  Kerala: singleTownDistricts([
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Kannur",
    "Alappuzha",
    "Palakkad",
    "Malappuram",
    "Kottayam",
    "Pathanamthitta",
    "Idukki",
    "Ernakulam",
    "Wayanad",
    "Kasaragod",
  ]),
  Ladakh: { Leh: ["Leh"], Kargil: ["Kargil"] },
  "Madhya Pradesh": singleTownDistricts([
    "Bhopal",
    "Indore",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Satna",
    "Ratlam",
    "Rewa",
    "Singrauli",
    "Burhanpur",
    "Khandwa",
    "Chhindwara",
    "Vidisha",
  ]),
  Maharashtra: singleTownDistricts([
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Thane",
    "Solapur",
    "Kolhapur",
    "Amravati",
    "Akola",
    "Latur",
    "Sangli",
    "Jalgaon",
    "Ahmednagar",
    "Satara",
    "Ratnagiri",
    "Sindhudurg",
    "Beed",
    "Nanded",
    "Chandrapur",
  ]),
  Manipur: singleTownDistricts(["Imphal East", "Imphal West", "Bishnupur", "Thoubal", "Churachandpur", "Senapati", "Ukhrul"]),
  Meghalaya: singleTownDistricts(["Shillong", "Tura", "Jowai", "Nongstoin", "Williamnagar"]),
  Mizoram: singleTownDistricts(["Aizawl", "Lunglei", "Champhai", "Kolasib", "Serchhip"]),
  Nagaland: singleTownDistricts(["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Mon", "Wokha"]),
  Odisha: singleTownDistricts([
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Berhampur",
    "Sambalpur",
    "Puri",
    "Balasore",
    "Bhadrak",
    "Baripada",
    "Jharsuguda",
    "Angul",
    "Dhenkanal",
  ]),
  Puducherry: { Puducherry: ["Puducherry"], Karaikal: ["Karaikal"], Mahe: ["Mahe"], Yanam: ["Yanam"] },
  Punjab: singleTownDistricts([
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Hoshiarpur",
    "Pathankot",
    "Moga",
    "Firozpur",
    "Sangrur",
    "Kapurthala",
    "Faridkot",
  ]),
  Rajasthan: singleTownDistricts([
    "Jaipur",
    "Jodhpur",
    "Udaipur",
    "Kota",
    "Ajmer",
    "Bikaner",
    "Alwar",
    "Bhilwara",
    "Sikar",
    "Pali",
    "Tonk",
    "Sri Ganganagar",
    "Hanumangarh",
    "Bharatpur",
    "Chittorgarh",
    "Banswara",
    "Dausa",
    "Nagaur",
    "Jhunjhunu",
  ]),
  Sikkim: singleTownDistricts(["Gangtok", "Namchi", "Mangan", "Geyzing"]),
  "Tamil Nadu": singleTownDistricts([
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Tiruppur",
    "Vellore",
    "Erode",
    "Thoothukudi",
    "Dindigul",
    "Thanjavur",
    "Kancheepuram",
    "Cuddalore",
    "Karur",
    "Nagapattinam",
  ]),
  Telangana: singleTownDistricts([
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Mahabubnagar",
    "Nalgonda",
    "Adilabad",
    "Medak",
    "Rangareddy",
    "Sangareddy",
  ]),
  Tripura: singleTownDistricts(["Agartala", "Udaipur", "Dharmanagar", "Kailashahar", "Belonia"]),
  "Uttar Pradesh": singleTownDistricts([
    "Lucknow",
    "Kanpur",
    "Ghaziabad",
    "Agra",
    "Varanasi",
    "Meerut",
    "Allahabad",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Noida",
    "Firozabad",
    "Jhansi",
    "Mathura",
    "Ayodhya",
    "Mirzapur",
    "Sultanpur",
    "Etawah",
    "Sitapur",
    "Hardoi",
  ]),
  Uttarakhand: singleTownDistricts([
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Udham Singh Nagar",
    "Almora",
    "Pauri Garhwal",
    "Tehri Garhwal",
    "Pithoragarh",
    "Chamoli",
    "Rudraprayag",
  ]),
  "West Bengal": singleTownDistricts([
    "Kolkata",
    "Howrah",
    "Darjeeling",
    "Siliguri",
    "Asansol",
    "Durgapur",
    "Bardhaman",
    "Malda",
    "Murshidabad",
    "Jalpaiguri",
    "Hooghly",
    "Nadia",
    "Bankura",
    "Purulia",
    "Cooch Behar",
  ]),
};

function singleTownDistricts(names: string[]): DistrictMap {
  const out: DistrictMap = {};
  for (const n of names) out[n] = [n];
  return out;
}

export function getDistricts(state: string): string[] {
  return Object.keys(IN_DISTRICTS[state] ?? {}).sort();
}

export function getTowns(state: string, district: string): string[] {
  return IN_DISTRICTS[state]?.[district] ?? [];
}
